// The reference-manifest emitter: turns a build-time enumeration of
// client/server references into an EMITTED registration module whose loads are
// STATIC imports. The artifact seals a closed dictionary with zero dynamic
// `import()`, so it works in runtimes that forbid runtime module loading
// (e.g. Cloudflare Workers) and makes the whole reference graph visible to the
// consumer's bundler.
//
// rsl stays transport-agnostic here: it does NOT discover modules (the
// consumer's bundler/loader does that); it turns records into an artifact. The
// gate is injected by the caller of the emitted `registerReferences` — there is
// no module-global gate.

import type { ReferenceKind } from "../references/index.js";

export type ManifestEntry = {
  /** Hosted id (the loader's `moduleID` output) — the gate key. */
  id: string;
  /**
   * Import specifier for the REAL module, resolvable from the emitted
   * module's location (relative path, or a bare/absolute specifier the
   * consumer's bundler resolves). Never derived from the incoming id.
   */
  specifier: string;
  kind: ReferenceKind;
  /**
   * The exports the build saw. Always emitted, so the sealed gate narrows
   * resolution to exactly this list (the per-export allowlist) instead of
   * "any reference export of a registered module".
   */
  exportNames: readonly string[];
};

/**
 * Codegen the registration module for a set of reference entries. The result
 * is ESM source: one static namespace import per entry plus an exported
 * `registerReferences(gate, { seal = true })` that registers every entry
 * against the injected gate and seals it. Write it wherever the entry
 * specifiers resolve from, then import it in the ssr/browser bundle.
 */
export function emitReferenceManifest(
  entries: readonly ManifestEntry[],
): string {
  const seen = new Set<string>();
  for (const entry of entries) {
    if (seen.has(entry.id)) {
      throw new Error(
        `Duplicate manifest entry for id ${JSON.stringify(entry.id)}.`,
      );
    }
    seen.add(entry.id);
  }

  const imports = entries.map(
    (entry, i) => `import * as m${i} from ${JSON.stringify(entry.specifier)};`,
  );
  const registrations = entries.map(
    (entry, i) =>
      `  gate.register({ id: ${JSON.stringify(entry.id)}, kind: ${JSON.stringify(
        entry.kind,
      )}, exportNames: ${JSON.stringify(entry.exportNames)}, load: () => m${i} });`,
  );

  return [
    "// Generated by react-server-loader/manifest — do not edit.",
    ...imports,
    "",
    "export function registerReferences(gate, { seal = true } = {}) {",
    ...registrations,
    "  if (seal) gate.seal();",
    "}",
    "",
  ].join("\n");
}
