#!/usr/bin/env bash
set -euo pipefail

# Reset the facebook/react build checkout back to a clean upstream branch.
#
# build-rsl.sh builds from ../react by force-checking-out a ref (detached) and
# injecting the edge overlay (inject-edge-bundle.mjs), so after a release the
# checkout is left detached at the built ref and dirty with the overlay. A plain
# `git checkout main` then (a) lands on the STALE local `main` ref — the builds
# never move it — and (b) trips over the overlay's tracked edits. This returns
# the checkout to a pristine real branch at the current upstream tip.
#
# Usage:
#   ./scripts/react-reset-main.sh              # reset ../react to current origin/main
#   ./scripts/react-reset-main.sh v19.2.7      # reset to a tag/sha (detached, as git does for tags)
#   REACT_DIR=~/code/react ./scripts/react-reset-main.sh
#
# The overlay source files it removes are regenerated by inject-edge-bundle.mjs
# on the next build, so a clean wipe is safe. The clone stays shallow (fine for
# builds); pass nothing special — `git fetch --unshallow` only if you need full
# history.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PKG_DIR="$(dirname "$SCRIPT_DIR")"

REACT_DIR="${REACT_DIR:-$(dirname "$PKG_DIR")/react}"   # sibling ../react, like build-rsl.sh
REF="${1:-main}"

if [ ! -d "$REACT_DIR/.git" ]; then
  echo "ERROR: no git checkout at $REACT_DIR (set REACT_DIR to your react clone)." >&2
  exit 1
fi

# Guard: clean -fd deletes untracked files, so refuse to run anywhere that
# isn't actually a facebook/react checkout.
origin_url="$(git -C "$REACT_DIR" remote get-url origin 2>/dev/null || true)"
case "$origin_url" in
  *facebook/react*) ;;
  *)
    echo "ERROR: $REACT_DIR origin is '${origin_url:-<none>}', not facebook/react — refusing." >&2
    exit 1
    ;;
esac

echo "==> Resetting $REACT_DIR to upstream '$REF' ..."
git -C "$REACT_DIR" fetch --depth 1 origin "$REF"

if git -C "$REACT_DIR" show-ref --verify --quiet "refs/remotes/origin/$REF"; then
  # A branch (e.g. main): reset the local branch to upstream and switch to it,
  # discarding the dirty overlay (-f). No more stale ref, no detached HEAD.
  git -C "$REACT_DIR" checkout -f -B "$REF" "origin/$REF"
else
  # A tag or sha: upstream has no branch ref, so detached is correct.
  git -C "$REACT_DIR" checkout -f FETCH_HEAD
fi

# Remove the leftover untracked edge-overlay sources (regenerated on next build).
# No -x, so gitignored node_modules/ and build/ are left untouched.
git -C "$REACT_DIR" clean -fd

echo "==> Done. $REACT_DIR now at $(git -C "$REACT_DIR" rev-parse --short HEAD) ($(git -C "$REACT_DIR" describe --tags --always 2>/dev/null || echo "$REF")), tree clean."
git -C "$REACT_DIR" status --short --branch | head -1
